name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Проверка установки

    - name: Build Docker image
      run: docker build -t app-web:latest ./app

    - name: Start services with Docker Compose
      run: docker-compose -f ./app/docker-compose.yml up -d

    - name: Run migrations
      run: docker-compose -f ./app/docker-compose.yml exec web python manage.py migrate

    - name: Collect static files
      run: docker-compose -f ./app/docker-compose.yml exec web python manage.py collectstatic --noinput
